import Vue from 'vue'

Vue.config.ignoredElements = [
  'a-scene',
  'a-entity',
  'a-assets',
  'a-asset-item',
  'a-plane',
  'a-light',
  'a-image',
  'a-box',
  'a-sky',
  'a-ring',
  'a-circle',
  'a-sphere',
  'a-cone',
  'a-cursor',
  'a-gltf-model',
  'xrextras-capture-config',
  'xrextras-capture-preview',
  'xrextras-capture-button',
  'xrextras-named-image-target',
  'xrextras-target-video-fade',
  'xrextras-curved-target-container',
  'xrextras-target-mesh',
  'xrextras-opaque-background',
  'a-camera',
]
